spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: pl.mloza.hibernate.CustomPostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor.sql.BasicBinder: TRACE